<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <!-- For the hosting and options abstractions, from the shared framework the host runs on. -->
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    </ItemGroup>

</Project>
