<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ReceiptSplit\ReceiptSplit.csproj" />
        <ProjectReference Include="..\ReceiptSplit.Testing\ReceiptSplit.Testing.csproj" />
    </ItemGroup>

</Project>
