<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Magick.NET-Q8-AnyCPU" />
        <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ReceiptSplit.Extraction\ReceiptSplit.Extraction.csproj" />
    </ItemGroup>

</Project>
